#compose file for the storage node 

services:
  storagenode1:
    build:
      context: ./storagenode
      dockerfile: dockerfile
    container_name: storagenode1
    volumes:
      - storagenode1_data:/app/gridrock_data
    ports:
      - "127.0.0.1:50051:50051"
    environment:
      - NODE_ID=1
      - NODE_PORT=50051
      - NODE_PEERS=1:storagenode1:50051,2:storagenode2:50052,3:storagenode3:50053

  storagenode2:
    build:
      context: ./storagenode
      dockerfile: dockerfile
    container_name: storagenode2
    volumes:
      - storagenode2_data:/app/gridrock_data
    ports:
      - "127.0.0.1:50052:50052"
    environment:
      - NODE_ID=2
      - NODE_PORT=50052
      - NODE_PEERS=1:storagenode1:50051,2:storagenode2:50052,3:storagenode3:50053

  storagenode3:
    build:
      context: ./storagenode
      dockerfile: dockerfile
    container_name: storagenode3
    volumes:
      - storagenode3_data:/app/gridrock_data
    ports:
      - "127.0.0.1:50053:50053"
    environment:
      - NODE_ID=3
      - NODE_PORT=50053
      - NODE_PEERS=1:storagenode1:50051,2:storagenode2:50052,3:storagenode3:50053

volumes:
  storagenode1_data:
  storagenode2_data:
  storagenode3_data:


  
