[package]
name = "storagenode"
version = "0.1.0"
edition = "2024"

[dependencies]
raft = "0.7.0"
rocksdb = "0.24.0"
tokio = {version = "1.53.1", features = ["full"]}
tonic = { version = "0.14.6", features = ["default"] }
prost = "0.14"
tonic-prost = "0.14.6"
tempfile = "3.27.0"

[build-dependencies]
tonic-prost-build = "0.14.6"
